version: '3.8'

services:
  web:
    build: .
    container_name: dunviidy_flask
    volumes:
      -  /home/dunviidy/MediaCMS/video_store:/video_store
      - ./templates:/app/templates
    expose:
      - "5000"
    restart: always

  nginx:
    image: nginx:alpine
    container_name: dunviidy_nginx
    ports:
      - "8088:8088"  
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
    restart: always
